### ISSUE TITLE
Use for backup

### ISSUE THREAD

**Issue by shlomiw** [olavloite/spanner-jdbc-converter#1]
Hi,

Since Spanner doesn't have a built-in solution, I'm looking for one.

Do you actually use this project for backup?

How much stress would it add while the DB is **online** and serving operational requests?

Thanks!

**Comment by olavloite** [comment]
Hi,
I use(d) this project for uploading and downloading development databases. I have not used it to create backups in a production environment. I did some tests on how much load it generated on my 1-node development instance, and I was never able to generate more than 50% load during my uploads. Downloads generated a lot less load.
The biggest problem you might run into when trying to generate a backup in this way, is that you would preferably use a read-only transaction on Cloud Spanner that lasts for the entire backup process, so that you know that you are downloading a snapshot of a consistent state of the database. Google Cloud Spanner garbage collects snapshots of data that are older than 1 hour, meaning that a read only transaction that lasts for more than 1 hour will probably be cancelled by Cloud Spanner.

**Comment by shlomiw** [comment]
Ok, thanks for your input! I'll take it into account.
I wonder what (and if) people do in Production env.
